name: SVUT
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
#      - run: sudo add-apt-repository ppa:team-electronics/ppa -y
      - run: sudo apt-get update -q
      - run: sudo apt-get install iverilog
      - run: sudo apt-get install verilator
      - run: iverilog -V
      - run: bash regression.sh